//
// Created by Paolo Sbarzagli on 25/02/23.
//

#ifndef VIDEOGIOCO_LEVELHEADER_H
#define VIDEOGIOCO_LEVELHEADER_H

#define LEVEL_ONE_HUMOR 100;
#define LEVEL_ONE_ARRIVALS 5;   //FIXME change arrival time
#define LEVEL_ONE_MAX_TABLES 6;
#define LEVEL_ONE_TOT_CUSTOMERS 20;

#define LEVEL_TWO_HUMOR 80;
#define LEVEL_TWO_ARRIVALS 180;
#define LEVEL_TWO_MAX_TABLES 8;
#define LEVEL_TWO_TOT_CUSTOMERS 28;

#define LEVEL_THREE_HUMOR 60;
#define LEVEL_THREE_ARRIVALS 150;
#define LEVEL_THREE_MAX_TABLES 10;
#define LEVEL_THREE_TOT_CUSTOMERS 35;

enum Lvl {FIRST, SECOND, THIRD, GAME_END};

#endif //VIDEOGIOCO_LEVELHEADER_H
