//
// Created by Paolo Sbarzagli on 24/02/23.
//

#ifndef VIDEOGIOCO_MEALMENU_H
#define VIDEOGIOCO_MEALMENU_H

enum Apt {NACHOS};
enum Mn {HAMBURGER, MEAT, MEATBALLS, CHICKEN};
enum Dsr {CHOCOLATE_CAKE, CHEESE_CAKE, JELLY};
enum Drk {WATER, WINE, BEER, COKE};
enum Current {APPETIZER, MAIN_DISH, DESSERT, DRINK};

#endif //VIDEOGIOCO_MEALMENU_H
